---
- name: Install postgres
  hosts: database_servers
  become: true
  gather_facts: false
  roles:
    - postgres

- name: Deploy app tier
  hosts: app_servers
  gather_facts: false
  become: true
  roles:
    - tomcat
  tags:
    - app_servers

- name: Deploy HAProxy load balancer
  hosts: load_balancers
  gather_facts: false 
  become: true
  roles:
    - haproxy
  tags:
    - load_balancers
    
- name: End to end smoke tests
  hosts: app_servers:database_servers
  gather_facts: true
  become: true
  tags:
    - smoketest
  roles:
    - smoke_test

- name: End to end smoke tests
  hosts: app_servers
  become: false
  gather_facts: false
  tags:
    - smoketest
  roles:
    - smoke_test_app
