---
- import_playbook: in-memory-inventory.yml
  tags:
    - inventory
    - must

- name: Deploy Common repos
  hosts: apps:frontends:appdbs
  gather_facts: false
  become: true
  tags:
    - common
  tasks:
    - name: Copy repo file
      copy:
        src: ./files/open_three-tier-app.repo
        dest: /etc/yum.repos.d/open_three-tier-app.repo

- name: Install postgres
  hosts: appdbs
  become: true
  gather_facts: false
  roles:
    - postgres

- name: Deploy app tier
  hosts: apps
  gather_facts: false
  become: true
  tags:
    - app_servers
  roles:
    - tomcat

- name: Deploy HAProxy load balancer
  hosts: frontends
  gather_facts: false 
  become: true
  tags:
    - load_balancers
  roles:
    - haproxy
  
- name: End to end smoke tests
  hosts: apps:appdbs
  gather_facts: true
  become: true
  tags:
    - smoketest
  roles:
    - smoke_test

- name: End to end smoke tests
  hosts: apps
  become: false
  gather_facts: false
  tags:
    - smoketest
  roles:
    - smoke_test_app
