---
# tasks file for smoke_test
- debug:
    msg: 
      - "IP is {{ hostvars['appdbs']['ansible_default_ipv4']['address'] }}"
      - "First App server  {{ groups.appdbs[0] }}" 
    verbosity: 2        
- name: Smoketest Postgres database
  postgresql_ping:
    db: flask_db
    login_host: "{{ hostvars['appdbs']['ansible_default_ipv4']['address'] }}"
    login_user: flask
    login_password: redhat
    ssl_mode: disable
  delegate_to: "{{ groups.appdbs[0] }}"
  run_once: true
  tags:
    - smoketest
